# -*- coding: utf-8 -*-
"""wisconsin_data_github.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18UJ-5i6_SyfU01PptfNxvR3ZCNirrRgc
"""

# Commented out IPython magic to ensure Python compatibility.
test_uri = "https://raw.githubusercontent.com/mark-watson/cancer-deep-learning-model/master/test.csv"
train_uri = "https://raw.githubusercontent.com/mark-watson/cancer-deep-learning-model/master/train.csv"


# %load_ext tensorboard

!pip install skimpy

from keras.models import Sequential # Keras by default imports and uses Tensorflow
from keras.layers import Dense, Dropout
from keras import optimizers
from keras.callbacks import TensorBoard
import tensorflow as tf
import pandas
import os
import datetime
from skimpy import skim

train_df = pandas.read_csv(train_uri, header=None)

skim(train_df)

train = train_df.values
X_train = train[:,0:9].astype(float) # 9 inputs
print("Number training examples:", len(X_train))
Y_train = train[:,-1].astype(float)  # one target output (0 for no cancer, 1 for malignant)
test = pandas.read_csv(test_uri, header=None).values
X_test = test[:,0:9].astype(float)
Y_test = test[:,-1].astype(float)

model = Sequential()
model.add(Dense(tf.constant(15), input_dim=tf.constant(9), activation='relu'))
model.add(Dense(tf.constant(15), input_dim=tf.constant(15), activation='relu'))
model.add(Dropout(0.2)),
model.add(Dense(tf.constant(1), activation='sigmoid'))
model.summary()

model.compile(optimizer='sgd',
              loss='mse',
              metrics=['accuracy'])

logdir = os.path.join("logs", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
callbacks = [TensorBoard(log_dir=logdir,histogram_freq=1,write_graph=True, write_images=True)]


model.fit(X_train, Y_train, batch_size=100, epochs=60, callbacks=callbacks)

# no cancer and malignant test samples:
y_predict = model.predict([[4,1,1,3,2,1,3,1,1], [3,7,7,4,4,9,4,8,1]])

print("* y_predict (should be close to [[0], [1]]):", y_predict)

# Commented out IPython magic to ensure Python compatibility.
# !pip install -U tensorboard-plugin-profile

# %tensorboard --logdir logs